runtime: python39

entrypoint: uvicorn upload:app --host 0.0.0.0 --port $PORT  # Using Uvicorn to serve FastAPI
service: backend
env_variables:
  GOOGLE_CLOUD_PROJECT: "temacloud-456115"  # Replace with your project ID

handlers:
  - url: /static
    static_dir: static/

  - url: /.*  # Catch-all for FastAPI
    script: auto
